Fix: TypeError: d.find is not a function
The `d.find` method is resulting in a TypeError because `d` is not an array.  This commit addresses the root cause of this error.